---
title: "Logistic"
author: "Stuart Miller"
date: "November 12, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, setup, warning=FALSE, message=FALSE, include=FALSE}

library(tidyverse)
library(gridExtra)
library(rebus)
library(car)
library(caret)
#library(doParallel)
library(pROC)

# load data
data <- 
  as.data.frame(
    read_csv('./diabetic_data.csv',
             col_types = cols(
               encounter_id = col_integer(),
               patient_nbr = col_integer(),
               race = col_factor(levels = c("?", "AfricanAmerican", "Asian", "Caucasian", "Hispanic", "Other")),
               gender = col_factor(levels = c("Male","Female")),
               age = col_factor(levels = c("[0-10)", "[10-20)", "[20-30)","[30-40)","[40-50)","[50-60)",
                                           "[60-70)","[70-80)","[80-90)","[90-100)")),
               weight = col_character(),
               admission_type_id = col_integer(),
               discharge_disposition_id = col_integer(),
               admission_source_id = col_integer(),
               time_in_hospital = col_integer(),
               payer_code = col_character()
             )
    )
  )

data <- read_csv('./diabetic_data.csv')
```

### Some Cleaning

Some cleaning from Dan's research

```{r}
# NA coersion
data <- data %>% mutate_all(~na_if(., '?'))
# Remove observations where discharge dispostion is related to hospice or death
data <- data %>% filter(!data$discharge_disposition_id %in% c('11','13','14','19','20','21'))
# Let's only use the first encounter for a given patient_nbr. Assume the first encounter is the lowest.
data <- data %>% group_by(patient_nbr) %>% filter(encounter_id == min(encounter_id))
# recode the outcomes to yes/no
data$outcome <- factor(ifelse(data$readmitted == "<30","Yes","No"))
```


```{r}
# create a test train split, do this before up sampling

trainIdx <- createDataPartition(data$outcome, p =0.75, list = F, times = 1)
train <- data[trainIdx, ]
test <- data[-trainIdx, ]

```


# Sampling

Some information on using caret for sampling for unbalanced datasets.

https://topepo.github.io/caret/subsampling-for-class-imbalances.html

```{r}
# upsample outsome 'yes'

up_train <- upSample(x = train[, -ncol(train)],
                     y = train$outcome)  
table(up_train$Class)
names(up_train)[length(names(up_train))] <- 'outcome'
```



```{r}
# glm logistic implementation

model.main<-glm(outcome ~ 
                  number_diagnoses + 
                  time_in_hospital + 
                  age +
                  admission_source_id, 
                data=up_train, 
                family = binomial(link="logit"))

summary(model.main)
(vif(model.main)[,3])^2
```


```{r}
# caret implementation

train.control <-trainControl(method = "cv",
                             number = 10,
                             summaryFunction = twoClassSummary,
                             classProbs = TRUE,
                             savePredictions = TRUE
                             )

model.cv <-train(y = up_train$outcome,
                 x = up_train[, c('age','time_in_hospital')],
                 method = 'glm',
                 metric = 'Spec',
                 family = 'binomial',
                 trControl = train.control
                 )

model.cv

preds <- predict(model.cv, test)

confusionMatrix(preds, test$outcome)
```

```{r}


plot.roc(model.cv$pred$obs,
         model.cv$pred$Yes)

```

```{r}
# caret implementation

train.control <-trainControl(method = "cv",
                             number = 10,
                             summaryFunction = twoClassSummary,
                             classProbs = TRUE,
                             savePredictions = TRUE
                             )

model.cv <-train(y = up_train$outcome,
                 x = up_train[, c('time_in_hospital',
                                  'num_lab_procedures',
                                  'number_diagnoses',
                                  'discharge_disposition_id')],
                 method = 'rf',
                 metric = 'Spec',
                 family = 'binomial',
                 trControl = train.control
                 )

model.cv

preds <- predict(model.cv, test)

confusionMatrix(preds, test$outcome)
```


```{r}


selected.Idx <- model.cv$pred$mtry == 4
plot.roc(model.cv$pred$obs[selected.Idx],
         model.cv$pred$Yes[selected.Idx])

```




